version: "3.5"

services:
  angular-app:
    container_name: screenzads-web-app
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./:/screenzads-web-app
    environment:
      - STYLE=css
